# Generated by Django 6.1.1 on 2026-09-21 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('REGISTER', 'Cadastro de conta'), ('ACCOUNT_ACTIVATED', 'Conta ativada'), ('SUBUSER_CREATED', 'Criação de usuário'), ('LOGIN_SUCCESS', 'Login bem-sucedido'), ('LOGIN_FAILED', 'Login inválido'), ('LOGIN_BLOCKED', 'Login bloqueado (rate limit)'), ('LOGOUT', 'Logout'), ('RECORD_CREATED', 'Registro criado'), ('RECORD_STATUS_CHANGED', 'Status de registro alterado'), ('RECORD_DELETED', 'Registro excluído')], db_index=True, max_length=30, verbose_name='ação')),
                ('actor', models.CharField(blank=True, db_index=True, max_length=254, verbose_name='ator (e-mail)')),
                ('source_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP de origem')),
                ('device', models.CharField(blank=True, max_length=255, verbose_name='dispositivo')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('reviewed', 'Em análise'), ('resolved', 'Resolvido')], db_index=True, default='open', max_length=20, verbose_name='situação')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ('-timestamp',),
            },
        ),
    ]
