# Generated by Django 6.1.1 on 2026-09-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0004_user_created_by_user_is_owner_user_owner_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('noob', 'Noob'), ('pro', 'Pro'), ('ultra', 'Ultra'), ('admin', 'Admin')], default='noob', max_length=10, verbose_name='role'),
        ),
    ]
